spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 3
      minimum-idle: 0
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 600000

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: false

    properties:
      hibernate:
        format_sql: false

server:
  tomcat:
    threads:
      max: 20
      min-spare: 2

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
    org.springframework.security: INFO
